sesion_07/config/urls.py
"""Project URL Configuration"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('movies.urls', 'movies'), namespace='movies'))
]

sesion_07/movies/urls.py
"""Movies app URL config"""

from django.urls import path

from . import views

urlpatterns = [
    path('', views.MovieListView.as_view(), name='list'),
]

sesion_07/movies/models.py
"""Movies app models"""

from django.db import models


class Movie(models.Model):
    """Movie model"""
    name = models.CharField('nombre', max_length=255)
    director = models.CharField('director', max_length=255)
    release_date = models.DateField('fecha de lanzamiento')
    created_at = models.DateTimeField('fecha de creación', auto_now_add=True)
    updated_at = models.DateTimeField('última actualización', auto_now=True)

    def __str__(self):
        """Returns a string representation of a movie"""
        return self.name

    class Meta:
        """Meta attributes of a movie"""
        verbose_name = 'película'

sesion_07/movies/views.py
"""Movies app views"""

from django.views.generic import ListView

from .models import Movie


class MovieListView(ListView):
    """Lists all movies"""
    model = Movie
    template_name = 'movies/list.html'

sesion_07/templates/base.html
<!doctype html>
<html lang="es-MX">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    {% block meta %} {% endblock meta %}
    {% block title %}
    <title>Bedu Movies</title>
    {% endblock title %}
  </head>
  <body>
    {% block content %} {% endblock content %}
    {% block scripts %} {% endblock scripts %}
  </body>
</html>

sesion_07/templates/movies/list.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Bedu Movies</h1>
    <p class="subtitle">Lista de películas</p>
    <div class="content">
      <ul>  
        {% for movie in movie_list %}
          <li>{{ movie.name }} de <strong>{{ movie.director }}</strong></li>
        {% endfor %}
      </ul>
    </div>
  </div>
</section>
{% endblock content %}