sesion_02/movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.list_movies, name='list'),
    path('create/', views.create, name='create'),
]

sesion_02/sesion_02/urls.py
"""sesion_02 URL Configuration"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include(('movies.urls', 'movies'), namespace='movies')),
    path('', include(('users.urls', 'users'), namespace='users')),
]

sesion_02/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.sign_in, name='login'),
    path('logout/', views.log_out, name='logout'),
]

sesion_02/movies/models.py
from django.db import models


class Director(models.Model):
    """Director model"""
    name = models.CharField(max_length=100)
    birthday = models.DateField()

    def __str__(self):
        return self.name


class Movie(models.Model):
    name = models.CharField(max_length=100)
    director = models.ForeignKey(to=Director, on_delete=models.CASCADE)
    year = models.PositiveSmallIntegerField()
    sinopsis = models.TextField()

    def __str__(self):
        return self.name + ' de ' + self.director.name

sesion_02/movies/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Movie, Director


@login_required
def list_movies(request):
    movies = Movie.objects.all()
    context = {'movies': movies}
    return render(request, 'movies/list.html', context)


@login_required
def create(request):
    context = {}

    if request.method == 'POST':
        name = request.POST.get('name')
        year = request.POST.get('year')
        year = int(year)
        sinopsis = request.POST.get('sinopsis')
        tarantino = Director.objects.get(id=1)

        movie = Movie.objects.create(
            name=name,
            year=year,
            sinopsis=sinopsis,
            director=tarantino
        )

        context['movie'] = movie

    return render(request, 'movies/create.html', context)

sesion_02/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect


def sign_in(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(
            request=request,
            username=username,
            password=password
        )

        if user:
            login(request, user)
            return redirect('movies:list')
        else:
            context['error'] = 'Credenciales inválidas'
    return render(request, 'users/login.html', context)


def log_out(request):
    logout(request)
    return redirect('users:login')

sesion_02/movies/templates/movies/create.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Crear</title>
</head>
<body>
  <header>
    <h1>Crear una película</h1>
    {% if movie %}
    <p>Se creo la película {{ movie.name }}</p>
    {% else %}
    <p>Ingresa la información de la película</p>
    {% endif %}
  </header>
  <section>
    <form action="{% url 'movies:create' %}" method="POST">
      {% csrf_token %}
      <div>
        <label for="name">Nombre:</label>
        <input type="text" name="name" id="name" required />
      </div>
      <div>
        <label for="year">Año:</label>
        <input type="number" name="year" id="year" required />
      </div>
      <div>
        <label for="sinopsis">Sinopsis:</label>
        <textarea name="sinopsis" id="sinopsis" cols="30" rows="10"></textarea>
      </div>
      <button type="submit">Enviar</button>
    </form>
  </section>
</body>
</html>

sesion_02/movies/templates/movies/list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Movies</title>
</head>
<body>
  <header>
    <h1>Peliculas</h1>
    <a href="{% url 'users:logout' %}">Cerrar sesión</a>
  </header>
  <section>
    <ul>
      {% for movie in movies %}
      <li>{{ movie.name }} por {{ movie.director.name }} en el {{ movie.year }}</li>
      {% endfor %}
    </ul>
  </section>
</body>
</html>

sesion_02/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
</head>
<body>
  <p>{{ error }}</p>
  <header>
    <h1>Iniciar sesión</h1>
  </header>
  <section>
    <form method="post">
      {% csrf_token %}
      <div>
        <label for="username">Username:</label>
        <input type="text" name="username" id="username" required />
      </div>
      <div>
        <label for="password">Password:</label>
        <input type="password" name="password" id="password" required />
      </div>
      <button type="submit">Iniciar sesión</button>
    </form>
  </section>
</body>
</html>